CREATE TABLE IF NOT EXISTS airports (
    new_airport_id SERIAL PRIMARY KEY,
	old_airport_id INTEGER,
    ident TEXT,
    type TEXT,
    name TEXT,
    latitude_deg NUMERIC,
    longitude_deg NUMERIC,
    elevation_ft INTEGER,
    continent TEXT,
    iso_country TEXT,
    iso_region TEXT,
    municipality TEXT,
    scheduled_service TEXT,
    gps_code TEXT,
    iata_code TEXT,
    local_code TEXT,
    home_link TEXT,
    wikipedia_link TEXT,
    keywords TEXT,
    magnetic_variation INTEGER
);
CREATE TABLE IF NOT EXISTS runways (
    new_runway_id SERIAL PRIMARY KEY,
    old_runway_id INTEGER,
    fk_airport_id INTEGER,
    airport_ident TEXT,
    length_ft INTEGER,
    width_ft INTEGER,
    surface TEXT,
    lighted TEXT,
    closed TEXT,
    runway_name TEXT,
    latitude_deg TEXT,
    longitude_deg TEXT,
    elevation_ft INTEGER,
    heading_degT NUMERIC,
    displaced_threshold_ft INTEGER,
    surface_friendly TEXT
);
