// <auto-generated />
using System;
using Airborn.web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace airborn.web.Migrations
{
    [DbContext(typeof(AirbornDbContext))]
    [Migration("20240519164608_AddCountries")]
    partial class AddCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Airborn.web.Models.Airport", b =>
                {
                    b.Property<int>("Airport_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("airport_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Airport_Id"));

                    b.Property<string>("Continent")
                        .HasColumnType("text")
                        .HasColumnName("continent");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("iso_country");

                    b.Property<int?>("FieldElevation")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_ft");

                    b.Property<string>("GPSCode")
                        .HasColumnType("text")
                        .HasColumnName("gps_code");

                    b.Property<string>("HomeLink")
                        .HasColumnType("text")
                        .HasColumnName("home_link");

                    b.Property<string>("IATACode")
                        .HasColumnType("text")
                        .HasColumnName("iata_code");

                    b.Property<string>("Ident")
                        .HasColumnType("text")
                        .HasColumnName("ident");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<double?>("Latitude_Deg")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude_deg");

                    b.Property<string>("LocalCode")
                        .HasColumnType("text")
                        .HasColumnName("local_code");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("municipality");

                    b.Property<double?>("Longitude_Deg")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude_deg");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("double precision")
                        .HasColumnName("magnetic_variation");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("iso_region");

                    b.Property<string>("ScheduledService")
                        .HasColumnType("text")
                        .HasColumnName("scheduled_service");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("WikipediaLink")
                        .HasColumnType("text")
                        .HasColumnName("wikipedia_link");

                    b.HasKey("Airport_Id")
                        .HasName("PK_Airport_Id");

                    b.HasIndex("Ident")
                        .IsUnique()
                        .HasDatabaseName("IX_Airport_Ident");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Airport_Type");

                    b.ToTable("airports");
                });

            modelBuilder.Entity("Airborn.web.Models.Country", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("country");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Country_Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("Ident")
                        .HasColumnType("text")
                        .HasColumnName("country_namet");

                    b.HasKey("Country_Id")
                        .HasName("PK_Country_Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Airborn.web.Models.Runway", b =>
                {
                    b.Property<int>("Runway_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("runway_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Runway_Id"));

                    b.Property<int>("Airport_Id")
                        .HasColumnType("integer")
                        .HasColumnName("fk_airport_id");

                    b.Property<string>("Airport_Ident")
                        .HasColumnType("text")
                        .HasColumnName("airport_ident");

                    b.Property<string>("Closed")
                        .HasColumnType("text")
                        .HasColumnName("closed");

                    b.Property<int?>("DisplacedThresholdFt")
                        .HasColumnType("integer")
                        .HasColumnName("displaced_threshold_ft");

                    b.Property<int?>("ElevationFt")
                        .HasColumnType("integer")
                        .HasColumnName("elevation_ft");

                    b.Property<double?>("HeadingDegreesTrue")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degt");

                    b.Property<double?>("Latitude_Deg")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude_deg");

                    b.Property<string>("Lighted")
                        .HasColumnType("text")
                        .HasColumnName("lighted");

                    b.Property<double?>("Longitude_Deg")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude_deg");

                    b.Property<int?>("RunwayLength")
                        .HasColumnType("integer")
                        .HasColumnName("length_ft");

                    b.Property<int?>("RunwayWidth")
                        .HasColumnType("integer")
                        .HasColumnName("width_ft");

                    b.Property<string>("Runway_Name")
                        .HasColumnType("text")
                        .HasColumnName("runway_name");

                    b.Property<string>("SurfaceText")
                        .HasColumnType("text")
                        .HasColumnName("surface");

                    b.Property<string>("Surface_Friendly")
                        .HasColumnType("text")
                        .HasColumnName("surface_friendly");

                    b.HasKey("Runway_Id")
                        .HasName("PK_Runway_Id");

                    b.HasIndex("Airport_Id")
                        .HasDatabaseName("IX_Runway_Airport_Id");

                    b.HasIndex("Runway_Name")
                        .HasDatabaseName("IX_Runway_Runway_Name");

                    b.ToTable("runways");
                });

            modelBuilder.Entity("Airborn.web.Models.Runway", b =>
                {
                    b.HasOne("Airborn.web.Models.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("Airport_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Runway_Airport_Id");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Airborn.web.Models.Airport", b =>
                {
                    b.Navigation("Runways");
                });
#pragma warning restore 612, 618
        }
    }
}
