name: HerokuContainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.*

      - name: Install EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 7.0.5

      - name: Restore dependencies
        run: dotnet restore airborn.web/airborn.web.csproj

      - name: Build
        run: dotnet build airborn.web/airborn.web.csproj --no-restore

      - name: Restore dotnet-ef tool
        run: dotnet tool restore

      - name: Set converted connection string
        run: |
          cd airborn.web  # Change to the project root directory
          dotnet add package Npgsql --version 5.0.10
          export CONVERTED_CONNECTION_STRING=$(dotnet run --no-build --no-restore --configuration Release -- Airborn.web.Models.DatabaseUtilities.GetConnectionString)

      - name: Run migrations
        run: |
          cd airborn.web  # Change to the project root directory
          dotnet ef database update -p airborn.web.csproj -- --connection "$CONVERTED_CONNECTION_STRING"

      - name: Build and deploy Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: 'airbornco'
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME

      - name: Run dotnet build separately
        run: dotnet build airborn.web/airborn.web.csproj
