name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_airborn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'airbornco' }}
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username ${{ secrets.HEROKU_API_KEY }} --password-stdin registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
