name: HerokuContainer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and deploy the Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'airbornco' }}
        run: |
          heroku container:login
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
